from dataclasses import dataclass
from enum import Enum

from pydantic import BaseModel


@dataclass
class IDs:
    sport: str = "id_sport"
    postcode: str = "id_postcode"
    country: str = "id_country"
    button_country: str = "id-button-country"
    modal_country: str = "modal-select-country"
    modal_country_select: str = "modal-country-select-input"


class Defaults(Enum):
    sport = "soccer"
    location = "Sydney_NSW_2000"
    country = "AU"


@dataclass()
class PostcodesDefault:
    AU: str = Defaults.location.value
    US: str = "Berkeley_California_94701"
    SG: str = "Bayfront Avenue_SG_018956"
    AD: str = "Canillo_Canillo_AD100"
    AI: str = "Anguilla_AI_AI-2640"
    AL: str = "Tirana Kamez_Tirana_1029"
    AR: str = "POZO CERCADO (EL CHORRO (F)_DPTO. RIVADAVIA (S))_A_3636"
    AS: str = "Pago Pago_AS_96799"
    AT: str = "Eisenstadt_Burgenland_7000"
    AX: str = "Mariehamn_Mariehamns stad_22100"
    AZ: str = "Abşeron_Abşeron_AZ 0100"
    BD: str = "Dhaka GPO_81_1000"
    BE: str = "Bruxelles_BRU_1000"
    BG: str = "Айтос / Ajtos_BGS_8500"
    BM: str = "Devonshire_Devonshire Parish_DV 01"
    BR: str = "Acrelândia_Acre_69945-000"
    BY: str = "Жабинка_Brest_225110"
    CA: str = "Eastern Alberta (St. Paul)_AB_T0A"
    CC: str = "Territory of Cocos (Keeling) Islands_CC_6799"
    CH: str = "Aarau_AG_5000"
    CL: str = "Valparaíso_Región de Valparaíso_2340000"
    CN: str = "Hefei_Anhui_230000"
    CO: str = "Leticia_Amazonas_910001"
    CR: str = "Alajuela_Provincia de Alajuela_20101"
    CX: str = "Territory of Christmas Island_CX_6798"
    CY: str = "Paralimni_Ammochostos_5280"
    CZ: str = "Žižkov_Hlavní město Praha_100 00"
    DE: str = "Mercedes-Benz Vertrieb NFZ GmbH_01_10875"
    DK: str = "København K_Capital Region_1050"
    DO: str = "Centro de Los Heroes_DO_10101"
    DZ: str = "Gasbet El Kaid_Adrar_1000"
    EC: str = "Española Hood-Puerto Baquerizo Moreno_Galápagos_200101"
    EE: str = "Kehra_Harju maakond_74305"
    ES: str = "Almeria_AN_4001"
    FI: str = "Helsinki_Uusimaa_100"
    FK: str = "Falkland Islands_FK_FIQQ 1ZZ"
    FM: str = "Kosrae_State of Kosrae_96944"
    FO: str = "Tórshavn_FO_100"
    FR: str = "Paris_Île-de-France_75000"
    GB: str = "Worthing_ENG_BN91"
    GF: str = "Cayenne_GF_97300"
    GG: str = "St Peter Port_GG_GY1"
    GI: str = "Gibraltar_GI_GX11 1AA"
    GL: str = "Santa Claus/Julemanden_GL_2412"
    GP: str = "Les Abymes_GP_97001 CEDEX"
    GS: str = "South Georgia and the South Sandwich Islands_GS_SIQQ 1ZZ"
    GT: str = "DEPTO DE ALTA VERAPAZ_DEPTO DE ALTA VERAPAZ_16000"
    GU: str = "Hagatna_Gu_96910"
    HK: str = "Hong Kong Special Administrative Region_HK_999077"
    HM: str = "Territory of Heard Island and McDonald Islands_HM_7151"
    HN: str = "La Ceiba_Atlántida_31101"
    HR: str = "Poljančani_Bjelovarsko-Bilogorska_43000"
    HT: str = "Port-de-Paix_Nord-Ouest_HT3110"
    HU: str = "Szárász_BA_7188"
    ID: str = "nan"
    IE: str = "Knock_C_F12"
    IM: str = "Douglas_IM_IM1"
    IN: str = "Sawai_Andaman & Nicobar Islands_744301"
    IO: str = "British Indian Ocean Territory_IO_BBND 1ZZ"
    IS: str = "Reykjavík - 1_IS_101"
    IT: str = "Barete_Abruzzi_67010"
    JE: str = "Jersey_JE_JE4"
    JP: str = "Rokujocho_Aichi Ken_490-1401"
    KE: str = "Nairobi Gpo_Nairobi_100"
    KR: str = "추자면_제주특별자치도_63000"
    LI: str = "Vaduz_Vaduz_9490"
    LK: str = "Kandy_Central Province_20000"
    LT: str = "Alytus_Alytus County_62001"
    LU: str = "Schouweiler_CA_L-4968"
    LV: str = "Aizkraukles stacija_01_LV-5101"
    MA: str = "Al Hoceima_Tanger-Tetouan-Al Hoceima_32000"
    MC: str = "Larvotto_Monaco_98000"
    MD: str = "Hirbovatul Nou_Anenii Noi_MD-6501"
    MH: str = "Majuro_Marshall Islands_96960"
    MK: str = "Skopje_MK_1000"
    MO: str = "Macau Special Administrative Region_MO_999078"
    MP: str = "Rota_Rota_96951"
    MQ: str = "Fort-de-France_MQ_97200"
    MT: str = "Attard_Attard_ATD"
    MW: str = "Dedza Township_C_209100"
    MX: str = "Zona Centro_Aguascalientes_20000"
    MY: str = "Nusajaya_JHR_79000"
    NC: str = "Bélep_Province Nord_98811"
    NF: str = "Territory of Norfolk Island_NF_2899"
    NL: str = "Assen_Drenthe_9401"
    NO: str = "Sandvika_Akershus_1300"
    NR: str = "Nauru_NR_NRU68"
    NU: str = "Niue_NU_9974"
    NZ: str = "Blockhouse Bay_E7_600"
    PA: str = "Bocas Del Toro (Cabecera)_Bocas Del Toro_1001"
    PE: str = "La Hoya_Amazonas_1000"
    PF: str = "Arue_Îles du Vent_98701"
    PH: str = "Laoag City_01_2900"
    PK: str = "Sui Gas Field Sibi_Balochistan_80000"
    PL: str = "Golnice_Lower Silesia_59-700"
    PM: str = "Miquelon_Miquelon-Langlade_97500"
    PN: str = "Pitcairn_Henderson_Ducie and Oeno Islands_PN_PCRN 1ZZ"
    PR: str = "Adjuntas_Adjuntas_601"
    PT: str = "Zona Industrial En 1 Norte_Aveiro_3750-000"
    PW: str = "Palau_PW_96940"
    RE: str = "Sainte-Clotilde_00_97491 CEDEX"
    RO: str = "Bărăbanţ_Alba_510001"
    RS: str = "Beograd_RS_11000"
    RU: str = "Майкоп_Адыгея Республика_385000"
    SE: str = "Fårö_05_624 66"
    SI: str = "Ljubljana - dostava_SI_1000"
    SJ: str = "Longyearbyen_Svalbard_9170"
    SK: str = "Dolná Mičiná_BC_974 01"
    SM: str = "San Marino_SM_47890"
    TC: str = "Turks and Caicos Islands_TC_TKCA 1ZZ"
    TH: str = "Pom Prap Sattru Phai_Bangkok_10100"
    TR: str = "Yeşilyurt_Adiyaman_2700"
    UA: str = "Черкаси_Cherkaska_18000"
    UY: str = "Limite Contestado_Artigas_40200"
    VA: str = "Citta Del Vaticano_VA_120"
    VI: str = "Christiansted_Vi_820"
    WF: str = "Alo_Circonscription d'Alo_98610"
    WS: str = "Independent State of Samoa_WS_AS 96799"
    YT: str = "Passamainty_Mayotte (general)_97605"
    ZA: str = "Pretoria_ZA_2"

    def __getitem__(self, key):
        return getattr(self, key)


class DropDownInfo(BaseModel):
    id: str
    question: str
    options: list[dict]
    multi: bool
    default: str
