from dataclasses import dataclass
from enum import Enum

from pydantic import BaseModel


@dataclass
class IDs:
    sport: str = "id_sport"
    postcode: str = "id_postcode"
    country: str = "id_country"
    button_country: str = "id-button-country"
    modal_country: str = "modal-select-country"
    modal_country_select: str = "modal-country-select-input"


class Defaults(Enum):
    sport = "soccer"
    location = "Sydney_NSW_2000_AU"
    country = "AU"


@dataclass()
class PostcodesDefault:
    AU: str = Defaults.location.value
    US: str = "Akutan_AK_99553_US"
    SG: str = "Bayfront Avenue_SG_018956_SG"
    AD: str = "Andorra la Vella_Andorra la Vella_AD500_AD"
    AI: str = "Anguilla_AI_AI-2640_AI"
    AL: str = "Tirana Kamez_Tirana_1029_AL"
    AR: str = "Isla martin garcia_Buenos Aires_B-1601_AR"
    AS: str = "Pago Pago_AS_96799_AS"
    AT: str = "Wien_Wieden_Wien_1040_AT"
    AX: str = "Mariehamn_Mariehamns stad_22100_AX"
    AZ: str = "Baki_Baki_AZ 1000_AZ"
    BD: str = "Dhaka GPO_81_1000_BD"
    BE: str = "Bruxelles_BRU_1000_BE"
    BG: str = "София / Sofija_SOF_1000_BG"
    BM: str = "Devonshire_Devonshire Parish_DV 01_BM"
    BR: str = "Guara_Distrito Federal_71000-000_BR"
    BY: str = "Minsk_Minsk_220021_BY"
    CA: str = "Ottawa (Overbrook)_ON_K1K_CA"
    CC: str = "Territory of Cocos (Keeling) Islands_CC_6799_CC"
    CH: str = "Aarau_AG_5000_CH"
    CL: str = "Santiago_Región Metropolitana_8320000_CL"
    CN: str = "Beijing_Beijing_100000_CN"
    CO: str = "Usaquen_Bogota_D.C._110111_CO"
    CR: str = "Carmen_Provincia de San José_10101_CR"
    CX: str = "Territory of Christmas Island_CX_6798_CX"
    CY: str = "Paralimni_Ammochostos_5280_CY"
    CZ: str = "Žižkov_Hlavní město Praha_100 00_CZ"
    DE: str = "Landgericht Berlin 1_16_10863_DE"
    DK: str = "København K_Capital Region_1050_DK"
    DO: str = "Res. Santo Domingo_DO_11114_DO"
    DZ: str = "Alger Asselah Hocine_Alger_16000_DZ"
    EC: str = "Cochapamba_Pichincha_170515_EC"
    EE: str = "Põhja-Tallinna_Harju maakond_10111_EE"
    ES: str = "Almeria_AN_4001_ES"
    FI: str = "Helsinki_Uusimaa_100_FI"
    FK: str = "Falkland Islands_FK_FIQQ 1ZZ_FK"
    FM: str = "Kosrae_State of Kosrae_96944_FM"
    FO: str = "Tórshavn_FO_100_FO"
    FR: str = "Paris_Île-de-France_75000_FR"
    GB: str = "Worthing_ENG_BN91_GB"
    GF: str = "Cayenne_GF_97300_GF"
    GG: str = "St Peter Port_GG_GY1_GG"
    GI: str = "Gibraltar_GI_GX11 1AA_GI"
    GL: str = "Santa Claus/Julemanden_GL_2412_GL"
    GP: str = "Les Abymes_GP_97001 CEDEX_GP"
    GS: str = "South Georgia and the South Sandwich Islands_GS_SIQQ 1ZZ_GS"
    GT: str = "DEPTO DE ALTA VERAPAZ_DEPTO DE ALTA VERAPAZ_16000_GT"
    GU: str = "Hagatna_Gu_96910_GU"
    HK: str = "Hong Kong Special Administrative Region_HK_999077_HK"
    HM: str = "Territory of Heard Island and McDonald Islands_HM_7151_HM"
    HN: str = "La Ceiba_Atlántida_31101_HN"
    HR: str = "Sljeme (Medvednica-Tomislavac)_Grad Zagreb_10000_HR"
    HT: str = "Port-de-Paix_Nord-Ouest_HT3110_HT"
    HU: str = "Szárász_BA_7188_HU"
    ID: str = "Gambir_ID_10110_ID"
    IE: str = "Dublin 1_L_D01_IE"
    IM: str = "Douglas_IM_IM1_IM"
    IN: str = "New Delhi G.P.O._Delhi_110001_IN"
    IO: str = "British Indian Ocean Territory_IO_BBND 1ZZ_IO"
    IS: str = "Reykjavík - 1_IS_101_IS"
    IT: str = "Roma_Lazio_118_IT"
    JE: str = "Jersey_JE_JE4_JE"
    JP: str = "Waseda Tsurumakicho_Tokyo To_162-0041_JP"
    KE: str = "Nairobi Gpo_Nairobi_100_KE"
    KR: str = "김포시_경기도_10100_KR"
    LI: str = "Vaduz_Vaduz_9490_LI"
    LK: str = "Kandy_Central Province_20000_LK"
    LT: str = "Alytus_Alytus County_62001_LT"
    LU: str = "Schouweiler_CA_L-4968_LU"
    LV: str = "Aizkraukles stacija_01_LV-5101_LV"
    MA: str = "Al Hoceima_Tanger-Tetouan-Al Hoceima_32000_MA"
    MC: str = "Larvotto_Monaco_98000_MC"
    MD: str = "Hirbovatul Nou_Anenii Noi_MD-6501_MD"
    MH: str = "Majuro_Marshall Islands_96960_MH"
    MK: str = "Skopje_MK_1000_MK"
    MO: str = "Macau Special Administrative Region_MO_999078_MO"
    MP: str = "Rota_Rota_96951_MP"
    MQ: str = "Fort-de-France_MQ_97200_MQ"
    MT: str = "Attard_Attard_ATD_MT"
    MW: str = "Dedza Township_C_209100_MW"
    MX: str = "Zona Centro_Aguascalientes_20000_MX"
    MY: str = "Kuala Lumpur_KUL_50100_MY"
    NC: str = "Bélep_Province Nord_98811_NC"
    NF: str = "Territory of Norfolk Island_NF_2899_NF"
    NL: str = "Assen_Drenthe_9401_NL"
    NO: str = "Sandvika_Akershus_1300_NO"
    NR: str = "Nauru_NR_NRU68_NR"
    NU: str = "Niue_NU_9974_NU"
    NZ: str = "Auckland_E7_1010_NZ"
    PA: str = "Bocas Del Toro (Cabecera)_Bocas Del Toro_1001_PA"
    PE: str = "La Hoya_Amazonas_1000_PE"
    PF: str = "Arue_Îles du Vent_98701_PF"
    PH: str = "Laoag City_01_2900_PH"
    PK: str = "Sui Gas Field Sibi_Balochistan_80000_PK"
    PL: str = "Golnice_Lower Silesia_59-700_PL"
    PM: str = "Miquelon_Miquelon-Langlade_97500_PM"
    PN: str = "Pitcairn_Henderson_Ducie and Oeno Islands_PN_PCRN 1ZZ_PN"
    PR: str = "Adjuntas_Adjuntas_601_PR"
    PT: str = "Zona Industrial En 1 Norte_Aveiro_3750-000_PT"
    PW: str = "Palau_PW_96940_PW"
    RE: str = "Sainte-Clotilde_00_97491 CEDEX_RE"
    RO: str = "Bărăbanţ_Alba_510001_RO"
    RS: str = "Beograd_RS_11000_RS"
    RU: str = "Майкоп_Адыгея Республика_385000_RU"
    SE: str = "Fårö_05_624 66_SE"
    SI: str = "Ljubljana - dostava_SI_1000_SI"
    SJ: str = "Longyearbyen_Svalbard_9170_SJ"
    SK: str = "Dolná Mičiná_BC_974 01_SK"
    SM: str = "San Marino_SM_47890_SM"
    TC: str = "Turks and Caicos Islands_TC_TKCA 1ZZ_TC"
    TH: str = "Pom Prap Sattru Phai_Bangkok_10100_TH"
    TR: str = "Yeşilyurt_Adiyaman_2700_TR"
    UA: str = "Черкаси_Cherkaska_18000_UA"
    UY: str = "Limite Contestado_Artigas_40200_UY"
    VA: str = "Citta Del Vaticano_VA_120_VA"
    VI: str = "Christiansted_Vi_820_VI"
    WF: str = "Alo_Circonscription d'Alo_98610_WF"
    WS: str = "Independent State of Samoa_WS_AS 96799_WS"
    YT: str = "Passamainty_Mayotte (general)_97605_YT"
    ZA: str = "Pretoria_ZA_2_ZA"

    def __getitem__(self, key):
        return getattr(self, key)


class DropDownInfo(BaseModel):
    id: str
    question: str
    options: list[dict]
    multi: bool
    default: str
