# language: yaml
name: Test the test version of the Extreme Heat Tool

on:
  workflow_run:
    workflows: [ "Deploy Test Version" ]
    types:
      - completed

jobs:
  deploy:
    name: Deploying Test 🚀 SMA
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: "pipenv"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
          pipenv install playwright

      - name: Ensure browsers are installed
        run: pipenv run playwright install --with-deps

      - name: Run your playwright tests
        run: pipenv run pytest --base-url https://extreme-heat-tool-test-987661761927.asia-southeast1.run.app/

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/